# Generated by Django 3.0.5 on 2020-04-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('icon', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=200)),
                ('url', models.SlugField()),
                ('pub_date', models.DateTimeField()),
                ('votes_toal', models.IntegerField()),
                ('body', models.TextField(max_length=40000)),
            ],
        ),
    ]
