# Generated by Django 3.0.5 on 2020-04-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200422_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='votes_toal',
            field=models.IntegerField(default=1),
        ),
    ]
